//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Famnances.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Landing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Famnances.Resources.Views.Home.Landing", typeof(Landing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define whatever cycle makes sense for you, and compare one period to the next in a couple of clicks..
        /// </summary>
        public static string Feature1_Body {
            get {
                return ResourceManager.GetString("Feature1_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods, not just months.
        /// </summary>
        public static string Feature1_Title {
            get {
                return ResourceManager.GetString("Feature1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track what repeats every period alongside the unexpected, without doing the math yourself..
        /// </summary>
        public static string Feature2_Body {
            get {
                return ResourceManager.GetString("Feature2_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income and expenses, fixed or everyday.
        /// </summary>
        public static string Feature2_Title {
            get {
                return ResourceManager.GetString("Feature2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Vacation,&quot; &quot;School,&quot; &quot;Emergencies&quot; — every goal is kept separate from this week&apos;s spending..
        /// </summary>
        public static string Feature3_Body {
            get {
                return ResourceManager.GetString("Feature3_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings with a name and a goal.
        /// </summary>
        public static string Feature3_Title {
            get {
                return ResourceManager.GetString("Feature3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your partner or family into the same &quot;Home&quot; — everyone sees the same budget..
        /// </summary>
        public static string Feature4_Body {
            get {
                return ResourceManager.GetString("Feature4_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One household, several people.
        /// </summary>
        public static string Feature4_Title {
            get {
                return ResourceManager.GetString("Feature4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the whole app&apos;s language without losing a single piece of data — for homes where more than one is spoken..
        /// </summary>
        public static string Feature5_Body {
            get {
                return ResourceManager.GetString("Feature5_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish, English, or French.
        /// </summary>
        public static string Feature5_Title {
            get {
                return ResourceManager.GetString("Feature5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-handed navigation, with what you use most always a thumb away..
        /// </summary>
        public static string Feature6_Body {
            get {
                return ResourceManager.GetString("Feature6_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed for your phone.
        /// </summary>
        public static string Feature6_Title {
            get {
                return ResourceManager.GetString("Feature6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No improvised spreadsheets, no generic apps half-translated. Famnances was built around how a real family actually organizes its money..
        /// </summary>
        public static string Features_SectionSubtitle {
            get {
                return ResourceManager.GetString("Features_SectionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four pieces, one clear picture.
        /// </summary>
        public static string Features_SectionTitle {
            get {
                return ResourceManager.GetString("Features_SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string FinalCta_CreateAccount {
            get {
                return ResourceManager.GetString("FinalCta_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore as a guest.
        /// </summary>
        public static string FinalCta_CtaGuest {
            get {
                return ResourceManager.GetString("FinalCta_CtaGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forms. No email. The real app, ready for you to use..
        /// </summary>
        public static string FinalCta_Subtitle {
            get {
                return ResourceManager.GetString("FinalCta_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come in and see your own .
        /// </summary>
        public static string FinalCta_Title1 {
            get {
                return ResourceManager.GetString("FinalCta_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period, right now..
        /// </summary>
        public static string FinalCta_Title2 {
            get {
                return ResourceManager.GetString("FinalCta_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2026 Famnances. An actively developed personal project..
        /// </summary>
        public static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Footer_LanguageHeading {
            get {
                return ResourceManager.GetString("Footer_LanguageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string Footer_LegalHeading {
            get {
                return ResourceManager.GetString("Footer_LegalHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made between Bogotá and Mississauga..
        /// </summary>
        public static string Footer_MadeIn {
            get {
                return ResourceManager.GetString("Footer_MadeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Footer_ProductHeading {
            get {
                return ResourceManager.GetString("Footer_ProductHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your family&apos;s budget, in the language you think it in..
        /// </summary>
        public static string Footer_Tagline {
            get {
                return ResourceManager.GetString("Footer_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try as a guest.
        /// </summary>
        public static string Footer_TryGuest {
            get {
                return ResourceManager.GetString("Footer_TryGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free to start · no card required.
        /// </summary>
        public static string Hero_Badge {
            get {
                return ResourceManager.GetString("Hero_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore as a guest.
        /// </summary>
        public static string Hero_CtaGuest {
            get {
                return ResourceManager.GetString("Hero_CtaGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how it works.
        /// </summary>
        public static string Hero_CtaHowItWorks {
            get {
                return ResourceManager.GetString("Hero_CtaHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email, no password — you&apos;re using the real app right away..
        /// </summary>
        public static string Hero_Note {
            get {
                return ResourceManager.GetString("Hero_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famnances organizes your household&apos;s budget, expenses, and savings by period — and it speaks Spanish, English, or French, whichever language your numbers think in at home..
        /// </summary>
        public static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all in one place.
        /// </summary>
        public static string Hero_TitleHighlight {
            get {
                return ResourceManager.GetString("Hero_TitleHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your family&apos;s finances,.
        /// </summary>
        public static string Hero_TitlePart1 {
            get {
                return ResourceManager.GetString("Hero_TitlePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in your language..
        /// </summary>
        public static string Hero_TitlePart2 {
            get {
                return ResourceManager.GetString("Hero_TitlePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string HeroCard_Available {
            get {
                return ResourceManager.GetString("HeroCard_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current period.
        /// </summary>
        public static string HeroCard_CurrentPeriod {
            get {
                return ResourceManager.GetString("HeroCard_CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July 2026.
        /// </summary>
        public static string HeroCard_MonthLabel {
            get {
                return ResourceManager.GetString("HeroCard_MonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergencies.
        /// </summary>
        public static string HeroCard_PocketEmergency {
            get {
                return ResourceManager.GetString("HeroCard_PocketEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string HeroCard_PocketSchool {
            get {
                return ResourceManager.GetString("HeroCard_PocketSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string HeroCard_PocketVacation {
            get {
                return ResourceManager.GetString("HeroCard_PocketVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent — $1,656 of $2,400.
        /// </summary>
        public static string HeroCard_Spent {
            get {
                return ResourceManager.GetString("HeroCard_Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famnances is the app for managing your family&apos;s budget, expenses, and savings, in the language you speak at home..
        /// </summary>
        public static string Meta_Description {
            get {
                return ResourceManager.GetString("Meta_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famnances — Your family&apos;s finances, all in one place.
        /// </summary>
        public static string Meta_Title {
            get {
                return ResourceManager.GetString("Meta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Nav_HowItWorks {
            get {
                return ResourceManager.GetString("Nav_HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string Nav_Stories {
            get {
                return ResourceManager.GetString("Nav_Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try without signing up.
        /// </summary>
        public static string Nav_TryWithoutSignup {
            get {
                return ResourceManager.GetString("Nav_TryWithoutSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who it&apos;s for.
        /// </summary>
        public static string Nav_WhoItsFor {
            get {
                return ResourceManager.GetString("Nav_WhoItsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Famnances exists.
        /// </summary>
        public static string Story_Badge {
            get {
                return ResourceManager.GetString("Story_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a family moves to a new country, something curious happens with money: the numbers change currency, but the conversations about the budget stay in the language of home. You still talk about &quot;groceries&quot; or &quot;savings for school&quot; in Spanish, even if the bank statement arrives in English..
        /// </summary>
        public static string Story_Body1 {
            get {
                return ResourceManager.GetString("Story_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That mismatch is exactly the problem Famnances set out to solve — not just for accessibility&apos;s sake, but because a real budgeting tool has to respect that the language of money and the language of the heart don&apos;t always match..
        /// </summary>
        public static string Story_Body2 {
            get {
                return ResourceManager.GetString("Story_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s why the app is built around the period — the unit of time a family actually thinks about its money in — and the household, not the individual user, as the unit that shares that budget, rather than the bank account..
        /// </summary>
        public static string Story_Body3 {
            get {
                return ResourceManager.GetString("Story_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It started as a way to organize my own household&apos;s accounts — between two languages and two countries. If it works the same way for you, that&apos;s exactly what it&apos;s here for..
        /// </summary>
        public static string Story_Quote {
            get {
                return ResourceManager.GetString("Story_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Sebastián, creator of Famnances.
        /// </summary>
        public static string Story_QuoteAuthor {
            get {
                return ResourceManager.GetString("Story_QuoteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A family budget shouldn&apos;t have to live across three different apps..
        /// </summary>
        public static string Story_Title {
            get {
                return ResourceManager.GetString("Story_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets by period.
        /// </summary>
        public static string Trust_BudgetsByPeriod {
            get {
                return ResourceManager.GetString("Trust_BudgetsByPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built for households.
        /// </summary>
        public static string Trust_MadeForHouseholds {
            get {
                return ResourceManager.GetString("Trust_MadeForHouseholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings by goal.
        /// </summary>
        public static string Trust_SavingsByGoal {
            get {
                return ResourceManager.GetString("Trust_SavingsByGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data, only yours.
        /// </summary>
        public static string Trust_YourDataOnly {
            get {
                return ResourceManager.GetString("Trust_YourDataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who it&apos;s for.
        /// </summary>
        public static string WhoItsFor_Badge {
            get {
                return ResourceManager.GetString("WhoItsFor_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string WhoItsFor_PhoneAvailable {
            get {
                return ResourceManager.GetString("WhoItsFor_PhoneAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current period.
        /// </summary>
        public static string WhoItsFor_PhoneCurrentPeriod {
            get {
                return ResourceManager.GetString("WhoItsFor_PhoneCurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groceries.
        /// </summary>
        public static string WhoItsFor_PhoneGroceries {
            get {
                return ResourceManager.GetString("WhoItsFor_PhoneGroceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July 2026.
        /// </summary>
        public static string WhoItsFor_PhoneMonth {
            get {
                return ResourceManager.GetString("WhoItsFor_PhoneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string WhoItsFor_PhoneVacation {
            get {
                return ResourceManager.GetString("WhoItsFor_PhoneVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your budget gets talked about in Spanish at home but your statements arrive in English, Famnances doesn&apos;t make you translate in your head..
        /// </summary>
        public static string WhoItsFor_Step1Body {
            get {
                return ResourceManager.GetString("WhoItsFor_Step1Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families juggling accounts in more than one language.
        /// </summary>
        public static string WhoItsFor_Step1Title {
            get {
                return ResourceManager.GetString("WhoItsFor_Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One shared household, one single &quot;how much do we have left&quot; number — no screenshots, no voice notes..
        /// </summary>
        public static string WhoItsFor_Step2Body {
            get {
                return ResourceManager.GetString("WhoItsFor_Step2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couples who want to see the same thing.
        /// </summary>
        public static string WhoItsFor_Step2Title {
            get {
                return ResourceManager.GetString("WhoItsFor_Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sign-up, no card: come in as a guest and you&apos;re already moving through periods in a real budget..
        /// </summary>
        public static string WhoItsFor_Step3Body {
            get {
                return ResourceManager.GetString("WhoItsFor_Step3Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone who wants to start today.
        /// </summary>
        public static string WhoItsFor_Step3Title {
            get {
                return ResourceManager.GetString("WhoItsFor_Step3Title", resourceCulture);
            }
        }
    }
}
