//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Famnances.Resources.Views.Outflows.Components.Overspent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Famnances.Resources.Views.Outflows.Components.Overspent.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full expense.
        /// </summary>
        public static string How1 {
            get {
                return ResourceManager.GetString("How1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excess value.
        /// </summary>
        public static string How2 {
            get {
                return ResourceManager.GetString("How2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! You are going over your budget  by .
        /// </summary>
        public static string Statement1 {
            get {
                return ResourceManager.GetString("Statement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we need to decide what to do with this expense:.
        /// </summary>
        public static string Statement2 {
            get {
                return ResourceManager.GetString("Statement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take from another budget.
        /// </summary>
        public static string Where1 {
            get {
                return ResourceManager.GetString("Where1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take from a savings pocket.
        /// </summary>
        public static string Where2 {
            get {
                return ResourceManager.GetString("Where2", resourceCulture);
            }
        }
    }
}
