<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7f2fca8d-75d5-4e98-ad0e-7b69c63600ff</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\**" />
    <Content Remove="wwwroot\lib\**" />
    <EmbeddedResource Remove="wwwroot\lib\**" />
    <None Remove="wwwroot\lib\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\cs\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\de\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\es\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\fr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\it\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\ja\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\ko\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.Build.Locator.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.IO.Redist.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Newtonsoft.Json.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\pl\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\pt-BR\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\ru\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Buffers.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Collections.Immutable.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.CommandLine.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Memory.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Numerics.Vectors.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Threading.Tasks.Extensions.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\tr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\zh-Hans\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\zh-Hant\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\cs\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\de\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\es\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\fr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\it\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\ja\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\ko\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.Build.Locator.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll.config" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Newtonsoft.Json.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\pl\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\pt-BR\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\ru\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\System.Collections.Immutable.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\System.CommandLine.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\tr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\zh-Hans\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\jspar\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\zh-Hant\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\cs\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\de\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\es\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\fr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\it\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\ja\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\ko\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.Build.Locator.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Microsoft.IO.Redist.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\Newtonsoft.Json.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\pl\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\pt-BR\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\ru\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Buffers.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Collections.Immutable.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.CommandLine.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Memory.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Numerics.Vectors.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\System.Threading.Tasks.Extensions.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\tr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\zh-Hans\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-net472\zh-Hant\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\cs\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\de\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\es\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\fr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\it\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\ja\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\ko\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.Build.Locator.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll.config" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\Newtonsoft.Json.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\pl\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\pt-BR\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\ru\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\System.Collections.Immutable.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\System.CommandLine.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\tr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\zh-Hans\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\Sebastian Pardo\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.14.0\contentFiles\any\any\BuildHost-netcore\zh-Hant\System.CommandLine.resources.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Oauth2.v2" Version="1.68.0.1869" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.7" />
    <PackageReference Include="Microsoft.Build" Version="18.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.17.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NuGet.Packaging" Version="7.3.1" />
    <PackageReference Include="NuGet.Protocol" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Athentication.DataCore">
      <HintPath>..\..\MyApiServices\Athentication.DataCore\bin\Release\net10.0\Athentication.DataCore.dll</HintPath>
    </Reference>
    <Reference Include="Famnances.Core">
      <HintPath>..\..\Famnances_DataModel\Famnances.Core\bin\Release\net10.0\Famnances.Core.dll</HintPath>
    </Reference>
    <Reference Include="Famnances.DataCore">
      <HintPath>..\..\Famnances_DataModel\Famnances.DataCore\bin\Release\net10.0\Famnances.DataCore.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Controllers\UsersController.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UsersController.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Helpers\PrettyError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PrettyError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ViewModels\Introduction\SavingsLabels.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SavingsLabels.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ViewModels\Savings\SavingsLabels.Designer.cs">
      <DependentUpon>SavingsLabels.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ViewModels\Users\CreateLabels.Designer.cs">
      <DependentUpon>CreateLabels.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Budgets\Edit.Designer.cs">
      <DependentUpon>Edit.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Budgets\Create.Designer.cs">
      <DependentUpon>Create.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Budgets\Details.Designer.cs">
      <DependentUpon>Details.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Budgets\Index.Designer.cs">
      <DependentUpon>Index.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Home\Landing.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Landing.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\IncomeDiscounts\EDit.Designer.cs">
      <DependentUpon>Edit.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\IncomeDiscounts\Create.Designer.cs">
      <DependentUpon>Create.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\IncomeDiscounts\Index.Designer.cs">
      <DependentUpon>Index.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Inflows\CreateFixedIncomes.Designer.cs">
      <DependentUpon>CreateFixedIncomes.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Inflows\EditFixedIncomes.Designer.cs">
      <DependentUpon>EditFixedIncomes.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Inflows\Edit.Designer.cs">
      <DependentUpon>Edit.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Inflows\Create.Designer.cs">
      <DependentUpon>Create.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Inflows\IndexFixedIncomes.Designer.cs">
      <DependentUpon>IndexFixedIncomes.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Inflows\Index.Designer.cs">
      <DependentUpon>Index.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Introduction\Summary.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Summary.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Outflows\Create.Designer.cs">
      <DependentUpon>Create.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Outflows\EditFixedExpenses.Designer.cs">
      <DependentUpon>EditFixedExpenses.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Outflows\DetailsFixedExpenses.Designer.cs">
      <DependentUpon>DetailsFixedExpenses.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Outflows\Edit.Designer.cs">
      <DependentUpon>Edit.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Outflows\CreateFixedExpenses.Designer.cs">
      <DependentUpon>CreateFixedExpenses.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Outflows\IndexFixedExpenses.Designer.cs">
      <DependentUpon>IndexFixedExpenses.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Outflows\Index.Designer.cs">
      <DependentUpon>Index.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\Edit.Designer.cs">
      <DependentUpon>Edit.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\EditPockets.Designer.cs">
      <DependentUpon>EditPockets.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\DetailsPocket.Designer.cs">
      <DependentUpon>DetailsPocket.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\CreatePockets.Designer.cs">
      <DependentUpon>CreatePockets.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\CreateFixed.Designer.cs">
      <DependentUpon>CreateFixed.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\EditFixed.Designer.cs">
      <DependentUpon>EditFixed.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\IndexPockets.Designer.cs">
      <DependentUpon>IndexPockets.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\IndexFixed.Designer.cs">
      <DependentUpon>IndexFixed.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\Index.Designer.cs">
      <DependentUpon>Index.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\Create.Designer.cs">
      <DependentUpon>Create.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Savings\PocketTransfer.Designer.cs">
      <DependentUpon>PocketTransfer.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Users\Invitations.Designer.cs">
      <DependentUpon>Invitations.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Users\EditHome.Designer.cs">
      <DependentUpon>EditHome.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Users\CreateHome.Designer.cs">
      <DependentUpon>CreateHome.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Users\Details.Designer.cs">
      <DependentUpon>Details.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Users\Create.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Create.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Introduction\Savings.Designer.cs">
      <DependentUpon>Savings.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Introduction\Discounts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Discounts.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ViewModels\Introduction\IncomeLabels.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IncomeLabels.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Home\ClosePeriod.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ClosePeriod.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Home\Index.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ViewModels\Introduction\DiscountsLabels.Designer.cs">
      <DependentUpon>DiscountsLabels.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Introduction\Budgets.Designer.cs">
      <DependentUpon>Budgets.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Introduction\FixedExpenses.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FixedExpenses.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Introduction\Index.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Index.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Introduction\Incomes.Designer.cs">
      <DependentUpon>Incomes.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Views\Introduction\PeriodSelector.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PeriodSelector.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Outflows\Components\Overspent\Default.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Default.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Shared\_IndexLayout.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_IndexLayout.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Views\Shared\_Layout.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Layout.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Controllers\UsersController.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UsersController.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Helpers\PrettyError.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PrettyError.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewModels\Introduction\SavingsLabels.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SavingsLabels.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewModels\Savings\SavingsLabels.resx">
      <LastGenOutput>SavingsLabels.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewModels\Users\CreateLabels.resx">
      <LastGenOutput>CreateLabels.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Budgets\Edit.resx">
      <LastGenOutput>Edit.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Budgets\Create.resx">
      <LastGenOutput>Create.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Budgets\Details.resx">
      <LastGenOutput>Details.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Budgets\Index.resx">
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Home\Landing.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Landing.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\IncomeDiscounts\Edit.resx">
      <LastGenOutput>EDit.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\IncomeDiscounts\Create.resx">
      <LastGenOutput>Create.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\IncomeDiscounts\Index.resx">
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Inflows\CreateFixedIncomes.resx">
      <LastGenOutput>CreateFixedIncomes.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Inflows\EditFixedIncomes.resx">
      <LastGenOutput>EditFixedIncomes.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Inflows\Edit.resx">
      <LastGenOutput>Edit.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Inflows\Create.resx">
      <LastGenOutput>Create.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Inflows\IndexFixedIncomes.resx">
      <LastGenOutput>IndexFixedIncomes.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Inflows\Index.resx">
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\Summary.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Summary.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\Create.resx">
      <LastGenOutput>Create.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\EditFixedExpenses.resx">
      <LastGenOutput>EditFixedExpenses.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\DetailsFixedExpenses.resx">
      <LastGenOutput>DetailsFixedExpenses.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\Edit.resx">
      <LastGenOutput>Edit.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\CreateFixedExpenses.resx">
      <LastGenOutput>CreateFixedExpenses.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\IndexFixedExpenses.resx">
      <LastGenOutput>IndexFixedExpenses.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\Index.resx">
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\Edit.resx">
      <LastGenOutput>Edit.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\EditPockets.resx">
      <LastGenOutput>EditPockets.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\DetailsPocket.resx">
      <LastGenOutput>DetailsPocket.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\CreatePockets.resx">
      <LastGenOutput>CreatePockets.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\CreateFixed.resx">
      <LastGenOutput>CreateFixed.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\EditFixed.resx">
      <LastGenOutput>EditFixed.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\IndexPockets.resx">
      <LastGenOutput>IndexPockets.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\IndexFixed.resx">
      <LastGenOutput>IndexFixed.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\Index.resx">
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\Create.resx">
      <LastGenOutput>Create.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Savings\PocketTransfer.resx">
      <LastGenOutput>PocketTransfer.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Users\Invitations.resx">
      <LastGenOutput>Invitations.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Users\EditHome.resx">
      <LastGenOutput>EditHome.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Users\CreateHome.resx">
      <LastGenOutput>CreateHome.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Users\Details.resx">
      <LastGenOutput>Details.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Users\Create.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Create.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\Savings.resx">
      <LastGenOutput>Savings.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\Discounts.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Discounts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewModels\Introduction\IncomeLabels.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>IncomeLabels.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Home\ClosePeriod.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ClosePeriod.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Home\Index.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewModels\Introduction\DiscountsLabels.resx">
      <LastGenOutput>DiscountsLabels.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\Budgets.resx">
      <LastGenOutput>Budgets.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\FixedExpenses.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>FixedExpenses.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\Index.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Index.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\Incomes.resx">
      <LastGenOutput>Incomes.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Introduction\PeriodSelector.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PeriodSelector.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Outflows\Components\Overspent\Default.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Default.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Shared\_IndexLayout.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_IndexLayout.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Views\Shared\_Layout.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Layout.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
